version: '2'

services:
  cpp-sgx:
    image: enclaive/cpp-sgx
    container_name: "cpp-sgx"
    privileged: true
    build:
      context: .
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"

  cpp-nosgx:
    image: enclaive/cpp-sgx
    container_name: "cpp-nosgx"
    privileged: true
    build:
      context: .
    entrypoint: ""
    command: "/app/app"
    devices:
      - "/dev/sgx_enclave:/dev/sgx_enclave"

